In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame({"actual" :  [0,0,0,0,1,1,1,0,1,1],
                   "predicted" : [0,0,0,0,0,1,1,1,0,1]})

In [4]:
df

actual  predicted
0       0          0
1       0          0
2       0          0
3       0          0
4       1          0
5       1          1
6       1          1
7       0          1
8       1          0
9       1          1

In [5]:
y = df['actual']
ypred = df['predicted']

In [6]:
df = pd.DataFrame({'x' : [25,26,27,16,14], "y" : [1,1,1,0,0]})

In [7]:
df

x  y
0  25  1
1  26  1
2  27  1
3  16  0
4  14  0

In [8]:
X = df[['x']]
y = df['y']

In [9]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X, y)

LogisticRegression()

In [10]:
model.intercept_

array([-13.72764095])

In [11]:
'''yhat = B1X + B0
     = 0.678X + (-13.72764095)'''

model.coef_

array([[0.67833386]])

In [12]:
# (optional)
model.predict_proba(X)   # check 0 and 1 based on (value > 0.5 = 1 )and (value < 0.5 = 0)

array([[0.03802643, 0.96197357],
       [0.01966528, 0.98033472],
       [0.01007698, 0.98992302],
       [0.94656123, 0.05343877],
       [0.98567001, 0.01432999]])

In [13]:
model.predict(X)

array([1, 1, 1, 0, 0], dtype=int64)

In [14]:
df['y_lr'] = 0.67833386 * df['x'] -13.72764095 
df

x  y      y_lr
0  25  1  3.230706
1  26  1  3.909039
2  27  1  4.587373
3  16  0 -2.874299
4  14  0 -4.230967

In [15]:
# backend code of model.predict_proba(X)  

from math import exp

df['p'] = 2.7182 * df['y_lr'] / (2.7182 * df['y_lr'] + 1)
df

x  y      y_lr         p
0  25  1  3.230706  0.897768
1  26  1  3.909039  0.913983
2  27  1  4.587373  0.925758
3  16  0 -2.874299  1.146780
4  14  0 -4.230967  1.095233

In [16]:
model.predict_proba(X)  

array([[0.03802643, 0.96197357],
       [0.01966528, 0.98033472],
       [0.01007698, 0.98992302],
       [0.94656123, 0.05343877],
       [0.98567001, 0.01432999]])

In [17]:
(14/20[(8/14)**2 + (6/14)**2] + 6/20[(2/6)**2 + (4/6)**2])/ 14/20 + 6/20

<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
C:\Users\SHRI\AppData\Local\Temp\ipykernel_15688\2578218130.py:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  (14/20[(8/14)**2 + (6/14)**2] + 6/20[(2/6)**2 + (4/6)**2])/ 14/20 + 6/20
C:\Users\SHRI\AppData\Local\Temp\ipykernel_15688\2578218130.py:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  (14/20[(8/14)**2 + (6/14)**2] + 6/20[(2/6)**2 + (4/6)**2])/ 14/20 + 6/20
C:\Users\SHRI\AppData\Local\Temp\ipykernel_15688\2578218130.py:1: SyntaxWarning: 'int' object is not subscriptable; perhaps you missed a comma?
  (14/20[(8/14)**2 + (6/14)**2] + 6/20[(2/6)**2 + (4/6)**2])/ 14/20 + 6/20
C:\User

TypeError: 'int' object is not subscriptable